#!/usr/bin/env bash

# Source this env to quickly build, clear and run by these aliases
# Run: source projenv

function build() {
    if [ ! -d build ]; then
        mkdir build
        cmake -B build .
    fi
    if [ -z $1 ]; then
        clean
        cmake --build build
    else
        clean
        cmake --build build --target $1
    fi
    
}

function clean() {
    if [ ! -d build ]; then
        echo "Error: Nothing to clean."
    else
        cmake --build build --target clean
    fi
}

function run() {
    if [ ! -f build/main ]; then
        echo "Error: Build first!"
    else
        build/main $1 $2 $3
    fi
}

function br() {
    build
    run $1 $2 $3
}